server:
  port: 8083
spring:
  application:
    name: jzyh-service-consumer
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://localhost:10086/eureka
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
